### ISSUE TITLE
Image Overlay ?

### ISSUE THREAD

**Issue by MentalGear** [phoboslab/WebGLImageFilter#13]
Hey, great (and fast!) Library!
I found this as most modern js image processing libraries are quite outdated, yours could be one of the best around if you gave it an update. :)
Also, using .png images as an overlay would be great as a new feature.

**Comment by phoboslab** [comment]
What sort of update? As far as I know, the library still works in all current browsers.

Adding "stickers" on top of images is way out of scope for this library - and easily solved without a library anyway. Just render the filtered image into a 2d canvas and draw the image on top.

**Comment by SunboX** [comment]
Would be nice to have this rendered in WebGL, too. With the possibility to use some Photoshop Layer Blend modes.

See: https://www.shadertoy.com/view/XdS3RW

**Comment by phoboslab** [comment]
Most(?) of these blend modes are now supported in Canvas2D as well.

https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation

**Comment by mreinstein** [comment]
I think this issue can be closed? Sounds like the library author has marked this out scope.
