### ISSUE TITLE
Licence and reuse

### ISSUE THREAD

**Issue by jacmendt** [phoboslab/WebGLImageFilter#15]
First of all thanks for the great work. In a project of mine I also need a couple of image filter, so I stumbled over your project. Unlucky my use case doesn't work so good with your API, so I started to work out a new API on a fork of this repo. It comes out, that I rewrote in my fork big parts of the hole library beside the shaders and filters. I thought now about to publish my results as a further image filter library (of course with reference to your work) or as a fork of you. I would prefer to publish it at a new project (of course under a open source licence), because I used other build tools and the API is mainly different from yours. Would this be okay?

Further I did like to know under which licence this project is published? Maybe you can add one. 

Thanks again for your work. jacmendt

**Comment by phoboslab** [comment]
I've added the license to the readme (MIT). It was previously only stated [in the source](https://github.com/phoboslab/WebGLImageFilter/blob/master/webgl-image-filter.js#L2).
