### ISSUE TITLE
is it possible to pass a canvas as the source rather than an image?

### ISSUE THREAD

**Issue by mreinstein** [phoboslab/WebGLImageFilter#19]
I have a game that I'm drawing to an html canvas, and I'd love to be be able to use this library to do post processing on it.

**Comment by phoboslab** [comment]
So, what stops you from doing that? :)

**Comment by mreinstein** [comment]
ahh, nice! 

I think my confusion came from the wording in the readme:
> apply them **to** an Image or Canvas element

I took this to mean that you could **output** to an image or canvas, but it wasn't clear to me that the **input** could be image or canvas.

**Comment by mreinstein** [comment]
by the way, amazing work on this library. It's rare that you find software developers that make tiny things that fit in almost a page and are both powerful and immediately understable. Well done!

**Comment by mreinstein** [comment]
If it would help I could send a PR that expands the usage instructions, and try to make this more explicit. Would that be useful/welcome?

**Comment by phoboslab** [comment]
Certainly! I'm not a native speaker, so any help improving the docs is appreciated :)
