### ISSUE TITLE
would you accept a PR for es modules support?

### ISSUE THREAD

**Issue by mreinstein** [phoboslab/WebGLImageFilter#20]
The majority of browsers natively support the new es modules feature, would you be willing/interested to accept a PR for this, or would you prefer to keep WebGLImageFilter as a window global?

**Comment by phoboslab** [comment]
I don't see much benefit for using ES Modules for such a simple, 1-file library; especially when all the Syntax is still ES5. Maybe for a rewrite, if I ever get interested in this again :)

**Comment by mreinstein** [comment]
> I don't see much benefit for using ES Modules for such a simple, 1-file library

I guess to me the benefits would be:
* being able to import this library in the same way I import all other libraries in my code
* getting rid of a window global

> especially when all the Syntax is still ES5

do you want es6 syntax? That's pretty much everywhere now, except for ie. If you want es6 I'm happy to send a PR. :)

**Comment by phoboslab** [comment]
Honestly, no. It wouldn't feel like "my" library anymore and I guess I would lose interested in maintaining it. Considering I'm not doing a good job at that anyway at the moment, feel free to fork it :)

**Comment by mreinstein** [comment]
no need, I'm not looking to move in and usurp your project. :)
