### ISSUE TITLE
any interest in a pixelation filter?

### ISSUE THREAD

**Issue by mreinstein** [phoboslab/WebGLImageFilter#22]
I've implemented a pixelation filter for my in-progress game. Here is a screen shot of the pixelation level being updated in real-time:

![pixelation](https://user-images.githubusercontent.com/718067/80255267-6ab52f80-8631-11ea-9ea3-a7b921092334.gif)

If this is something we want, it's a pretty small shader.

**Comment by phoboslab** [comment]
Neat! I'd merge a PR.
