### ISSUE TITLE
Why vertices with 4 coordinates ?

### ISSUE THREAD

**Issue by Jacques-deMontbron** [phoboslab/WebGLImageFilter#5]
Good morning !

I can't find any documentation on how your vertex array should work or what represent the v and w coordinates :

``` javascript
  // Create the vertex buffer for the two triangles [x, y, v, w] * 6
  var vertices = new Float32Array([
  -1, -1, 0, 1, 1, -1, 1, 1, -1, 1, 0, 0,
  -1, 1, 0, 0, 1, -1, 1, 1, 1, 1, 1, 0
  ]);
```

For me, vertices only need 2, or 3 coordinates with the depth. I guess you're not specifying any depth with these points, but I can't manage do find what v and w are. Can you give me a hint on this, please ? Thanks (a lot) in advance !

**Comment by SumeyyeBayrakdar** [comment]
Hi,
 i can't screen.css, whitebox.js and phoboslab.ico files.
can you share them? is it possible?
